### ISSUE TITLE
Connection forcibly aborted by remote host

### ISSUE THREAD

**Issue by racontre** [ErikPelli/fivesim#1]
This code:
`
client = FiveSim(api_key=API_KEY)
print(client.user.get_profile_data())
`
causes this error:
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

I am using a valid API

**Comment by ErikPelli** [comment]
Yeah, it happens when servers are overloaded, you should do a try catch in
a loop

**Comment by racontre** [comment]
Actually it turns out it was due to the website being blocked. This website must be unavailable in Russia, couldn't connect through home wifi or mobile data.
